# -*- coding: utf-8 -*-
"""DN_lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlQBdykMVNvLg7sl5hTZT78ub5Klrzze
"""

import torch
import torch.nn as nn
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

data = pd.read_csv('/content/drive/MyDrive/dataset_simple.csv', delimiter=',')

plt.figure(figsize=(10, 6))
plt.scatter(data['age'], data['income'], alpha=0.6, color='blue')
plt.xlabel('Возраст')
plt.ylabel('Доход')
plt.title('Зависимость дохода от возраста')
plt.grid(True, alpha=0.3)
plt.show()

X = data['age'].values.reshape(-1, 1)
Y = data['income'].values.reshape(-1, 1)

scaler_X = StandardScaler()
scaler_Y = StandardScaler()
norm_X = scaler_X.fit_transform(X)
norm_Y = scaler_Y.fit_transform(Y)

print(f'До нормализации: min={X.min()}, max={X.max()}, mean={X.mean()}')
print(f'После нормализации: min={norm_X.min()}, max={norm_X.max()}, mean={norm_X.mean()}')

class IncomePredict(nn.Module):
    def __init__(self):
        super(IncomePredict, self).__init__()
        self.layer1 = nn.Linear(1, 50)
        self.layer2 = nn.Linear(50, 25)
        self.layer3 = nn.Linear(25, 1)

    def forward(self, x):
        x = torch.relu(self.layer1(x))
        x = torch.relu(self.layer2(x))
        return self.layer3(x)

model = IncomePredict()
print(model)
print(f"Параметров: {sum(p.numel() for p in model.parameters())}")

X_tensor = torch.FloatTensor(norm_X)
Y_tensor = torch.FloatTensor(norm_Y)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

epochs = 1200
losses = []

for epoch in range(epochs):
    model.train()
    pred = model(X_tensor)
    loss = criterion(pred, Y_tensor)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    losses.append(loss.item())

    if epoch % 100 == 0:
        print(f'Эпоха {epoch} | Ошибка: {loss.item():.4f}')

model.eval()
with torch.no_grad():
    predictions = model(X_tensor[:5])
    print('Предсказания после обучения:', predictions.numpy().flatten())
    print('Реальные значения:', Y_tensor[:5].numpy().flatten())