# -*- coding: utf-8 -*-
"""DN_lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HhDEr-8ZE4iD3Lbls51yjfk0cANuFJRO
"""

import random

# 1. Создаем список, заполненный случайными числами
random_numbers = [random.randint(1, 100) for _ in range(20)]  # 20 случайных чисел от 1 до 100
print("Список случайных чисел:", random_numbers)

# 2. Суммируем только четные значения
even_sum = 0
for number in random_numbers:
    if number % 2 == 0:  # Проверяем, четное ли число
        even_sum += number

# 3. Выводим полученную сумму
print("Сумма четных чисел:", even_sum)

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv('/content/drive/MyDrive/iris.csv', delimiter=',')
y = data.iloc[:, 4].values
y = np.where(y == 'Iris-setosa', 1, -1)
X = data.iloc[:, [0, 1, 2]].values

def neuron(w, x):
    inp = w[0] + np.dot(w[1:], x)
    return 1 if inp >= 0 else -1

w = np.random.random(4)
eta = 0.01
wres = []

for xi, target, j in zip(X, y, range(X.shape[0])):
    predict = neuron(w, xi)
    w[1:] += eta * (target - predict) * xi
    w[0] += eta * (target - predict)
    if j % 10 == 0:
        wres.append(w.tolist())

plt.figure(figsize=(12, 8))
scatter = plt.scatter(X[:, 0], X[:, 1], c=X[:, 2], cmap='viridis', s=80, edgecolor='k', linewidth=0.7)

mask_setosa = (y == 1)
mask_not_setosa = (y == -1)

plt.scatter(X[mask_setosa, 0], X[mask_setosa, 1], c=X[mask_setosa, 2], cmap='viridis', marker='o', s=80, edgecolor='k', linewidth=0.7, label='Сетоса (1)')
plt.scatter(X[mask_not_setosa, 0], X[mask_not_setosa, 1], c=X[mask_not_setosa, 2], cmap='viridis', marker='s', s=80, edgecolor='k', linewidth=0.7, label='Не-Сетоса (-1)')

cbar = plt.colorbar(scatter)
cbar.set_label('Длина лепестка (третий признак)')

plt.xlabel('Длина чашелистика (первый признак)')
plt.ylabel('Ширина чашелистика (второй признак)')
plt.title('Визуализация 3D-данных в 2D: Цвет = значение третьего признака')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()